import './styles/consent.css';
import {readConfig,autoLoadCss} from './config'; import {ConsentStorage} from './storage'; import {initGtag,updateDenied,updateGranted} from './consent-state'; import {AnalyticsLoader} from './analytics-loader'; import {cleanupGaCookies} from './cookie-cleanup'; import {messages} from './i18n'; import {Banner} from './ui/banner'; import {SettingsDialog} from './ui/settings-dialog'; import type {ConsentDetails,ConsentState} from './types';
(function main(){if(window.__ASOPI_CONSENT_READY__)return; window.__ASOPI_CONSENT_READY__=true; const config=readConfig(); autoLoadCss(config); initGtag(); if(!config.measurementIdValid){const msg='[AsopiConsent] Invalid data-measurement-id. Expected ^G-[A-Z0-9]+$'; config.debug?console.warn(msg,{measurementId:config.measurementId}):console.warn(msg)} const storage=new ConsentStorage(config.storageKey,config.consentVersion); const loader=new AnalyticsLoader(config.debug); let stored=storage.read(); let state:ConsentState=stored.state; let updatedAt=stored.updatedAt; const listeners=new Set<(d:ConsentDetails)=>void>(); const m=messages[config.language]; let banner:Banner; let dialog:SettingsDialog;
 const details=():ConsentDetails=>({state,version:config.consentVersion,updatedAt,analyticsLoaded:loader.isLoaded()}); const emit=()=>{const d=details(); listeners.forEach(cb=>cb(d)); window.dispatchEvent(new CustomEvent('asopi-consent:change',{detail:d}))};
 const hide=()=>banner?.hide(); const grant=async()=>{if(!config.measurementIdValid)return; updateGranted(); const saved=storage.save('granted'); state=saved.state; updatedAt=saved.updatedAt; hide(); emit(); try{await loader.load(config.measurementId)}catch(e){if(config.debug)console.warn('[AsopiConsent] GA4 load failed',e)} emit()}; const deny=()=>{updateDenied(); const saved=storage.save('denied'); state=saved.state; updatedAt=saved.updatedAt; cleanupGaCookies(); hide(); emit(); if(config.reloadOnRevoke)location.reload()};
 const reset=()=>{storage.reset(); state='unknown'; updatedAt=null; updateDenied(); cleanupGaCookies(); banner.show(); emit()}; const openSettings=()=>dialog.open(); const closeSettings=()=>dialog.close();
 banner=new Banner(m,config.policyUrl,()=>{void grant()},deny); dialog=new SettingsDialog(m,config.policyUrl,()=>state,()=>{void grant(); dialog.close()},()=>{deny(); dialog.close()}); window.AsopiConsent={getState:()=>state,getDetails:details,grant,deny,reset,openSettings,closeSettings,onChange(cb){listeners.add(cb); return()=>listeners.delete(cb)}};
 if(state==='granted'&&config.measurementIdValid){updateGranted(); void loader.load(config.measurementId).then(emit).catch(e=>{if(config.debug)console.warn(e)})} else if(state==='unknown') { const show=()=>banner.show(); if(document.body)show(); else document.addEventListener('DOMContentLoaded',show,{once:true}) }
 window.dispatchEvent(new CustomEvent('asopi-consent:ready',{detail:details()}));})();
